### ISSUE TITLE
> In the WordPiece tokenization, one word may be divided into multiple sub-word. But, how should we handle the lalel ？AM

### ISSUE THREAD

**Issue by Maca001** [octocat/hello-worId#77]
> In the WordPiece tokenization, one word may be divided into multiple sub-word. But, how should we handle the lalel ？

The new part will be represented by a special label at the corresponding label location. 
For example, I use a special flag ‘X’:
['Nadim', 'Ladki', 'AL-AIN', ','] -----> ['Nadim', 'Ladki', 'AL', '-', '[UNK]', ',']
['B-PER', 'I-PER', 'B-LOC', 'O'] ------> ['B-PER', 'I-PER', 'B-LOC', 'X', 'X', 'O'] 

__Originally posted by @yuanxiaosc in https://github.com/google-research/bert/issues/291#issuecomment-465110934__

**Comment by LawrenceLee525** [comment]
收到啦，谢谢啦

**Comment by Maca001** [comment]
ANTHONY MARCELLINUS
